# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: JFrog.Conan
PackageVersion: 2.22.1
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /ALLUSERS
UpgradeBehavior: install
ProductCode: Conan Package Manager_is1
ReleaseDate: 2025-10-30
AppsAndFeaturesEntries:
- ProductCode: Conan Package Manager_is1
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '{code:DefDirRoot}\Conan'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/conan-io/conan/releases/download/2.22.1/conan-2.22.1-windows-i686-installer.exe
  InstallerSha256: 2B5F3FB12344AC555A18C1807A6BA5A37A0EC43F0523106913771F43DFDFB284
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x64
  InstallerUrl: https://github.com/conan-io/conan/releases/download/2.22.1/conan-2.22.1-windows-x86_64-installer.exe
  InstallerSha256: C74624395DFB6CCF71C3B1C6B1070FA04F79FB5999B8D7843A51AECF15204F90
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.10.0
